import Head from 'next/head'
import styles from '../styles/Home.module.css'
import type { ReactElement } from 'react'
import Layout from '../components/layout'

export default function Page() {
  return (
      <div className={styles.container}>
          <Head>
            <title>Next 101</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={styles.main}>
            Hello
          </main>
      </div>
  )
}

Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}


// import type { NextPage } from 'next'
// import Head from 'next/head'
// import styles from '../styles/Home.module.css'

// const Home: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Next 101</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>


//       </main>
//     </div>
//   )
// }

// export default Home
